### ISSUE TITLE
My Website Plan

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/web-design-2-independent-project#1]
@thatkidmadrid

[carboni-jessica-030-web-project.pdf](https://github.com/Jessica-Lee123/web-design-2-independent-project/files/7540064/carboni-jessica-030-web-project.pdf)

**Comment by thatkidmadrid** [comment]
| | 0 points | 1 points | 2 points | 3 points | Grade |
| --- | --- | --- | --- | --- | --- |
| **Content inventory** | Incomplete or missing | Rushed & too generic | **Specific but obviously lacking research** | Specific and appropriate, with good details | 2 |
| **Sitemap** | Incomplete or missing | Has only the pages we’re coding | Lots of important pages missing | Complete, organized and contains all necessary pages | 3 |
| **Homepage wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 2 |
| **Page 2 wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 1 |
| **Page 3 wireframe** | Incomplete or missing | Missing important pieces or poorly executed | Complete but not detailed enough | Complete, detailed, responsive, and a good representation to code from | 1 |
| **Logo** | Incomplete or missing | Only works well at one size | Small sizes are inconsistent with large sizes | Cohesive & uniform for all sizes, even if different | 3 |
| **Visual design** | Incomplete or missing | Missing important components or poorly executed | Average, could be more cohesive & considered | Cohesive & appropriate with a good sample of components | 2 |
| **Professionalism** | Rushed & poorly done | Okay | Average, could use more time spent | Clearly demonstrated lots of effort and consideration | 2 |

**Comment by thatkidmadrid** [comment]
- I'm giving you 3 for the sitemap, but you didn't simplify it like I had suggested,  but it technically meets the requirements for 3 points, although it gets confusing because it looks like there are links from logo to the other pages
- I am being generous with the 2 points for the home page, but I am missing things that help make sense of the wireframes like headings the content prioritization, and there are no examples of changing the layout between sizes. it seems like you just scaled the same layout - media queries is a topic we covered before reading week, so you should include some examples of changing styles at different screen sizes
- Although the logo is cohesive I have my concerns at the smallest size. there should be 4 sizes (256, 64, 32, 16) you have the logo framed in a circle in your home page wireframe, so maybe it would be good to include it in your logo examples too, especially for the smaller sizes
- I feel like I'm being very generous with the mood board as well - I'm missing some examples of components, iconography, imagery, etc
- I feel like I'm being very generous with the professionalism too, but you're not technically missing any sections, but hopefully you can agree that there are some pretty big things missing from the project plan.

Feel free to reach out to me if you need any clarification or want to refute any of the grades here. Sorry we didn't have enough time to get to you in class

**Comment by Jessica-Lee123** [comment]
@thatkidmadrid 
Hey Christian,
I could use some help. I am so sorry it's past the class time, but I only now feel like I need help(figures, I get it). 
I'm not sure why all my images are broken except my first one and why CSS isn't working. 

Also, I was one of those who was forgetting to commit, I tried to label what I remembered when committing. This would be so much easier in class!
I appreciate any help, brace yourself though it's messy!!! 

As a positive note, I got my 3 pages to link back to each other, that's a pretty big win for today! ;D

**Comment by thatkidmadrid** [comment]
Your logo in your home is referencing `logo.jpg` while in your images folder it's `logo.png` so just need to pay close attention to the file extensions here

for the images in your about page you need to use the `../` trick we went over in class to go back a level in your folder structure to then find the images folder. Right now it's looking for a folder like `/pages/images/me.jpg` so instead you should reference `../images/me.jpg` 
what this is doing is, going back a folder level, then looking for the images folder

This should also fix the references to you image folder in your portfolio page

**Comment by Jessica-Lee123** [comment]
@thatkidmadrid 
Hey Christian, 
I am having trouble getting my animated buttons to work on my other two pages, it only seems to be applied to my main page. Could you please let me know how to apply this? Also, I know it's a bit late but if you see anything else I can add to improve my mark, please let me know. I am currently also trying to figure out how to link my Flickr to my images. If you have any tips let me know, currently using google for help. Thank you :)

**Comment by thatkidmadrid** [comment]
You will want to make sure that you're using the same classes on your navigation on other pages to get them to behave the same. You will need to stay on top of keeping them all up to date with one another when you make a change. The way you had it set up, just adding the class `button` to a `ul` in your nave brought back the styling.

My advice would be to go over[ the rubric ](https://learn-the-web.algonquindesign.ca/courses/web-design-2/week-11/#code-your-project) to see where you can get more grades out of the project. You will want to take a look at the list of techniques we went over before reading week in the course overview to see what concepts you need to apply on your page. Right away, the first thing that stuck out to me is that you're not using any media queries so there is an opportunity to improve the site with that.

Also a very important thing you can do is make sure you throw your project folder into markbot to get guidance with what's left to do to meet the minimum requirements for the website.

Could you be more specific about what exactly you want to link to in flickr?

**Comment by Jessica-Lee123** [comment]
@thatkidmadrid 
I am stuck, I could use some help with my favicon. I even double checked it online and the code is the same as what I got from you in class. I applied it to all pages,  in the head, under title. Not sure what else I'm doing wrong there. 
I also tried to apply two media queries, so I must not have done those properly either if you didn't see them in my css. :( Failing at this.

**Comment by thatkidmadrid** [comment]
Please make new github issues if it's a new topic!

You may want to try moving your favicon files outside of your images folder and leave them at the root level of your project.

your second media query isn't closed (missing a `}`)

also, if you want the `.text` rule on line 150 to be part of your first media query, make sure it is with in the braces of the media query`{...}`

**Comment by thatkidmadrid** [comment]
also, maybe the changes aren't obvious enough for the media queries. I need to be able to see some obvious change in layout or sizing that optimizes your page for different screen sizes
