### ISSUE TITLE
Just noticed! Favicon not showing up! 

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/web-design-2-independent-project#14]
@thatkidmadrid
@anna-pokhilenko

Hey you two wonderful people, I could use a second pair of eyes to check out my favicon on all three pages, I believe it's the right code and in the right location up in the top, but it's still not showing up. 
Thank you kindly for your time. :)

**Comment by thatkidmadrid** [comment]
You shouldn't close issues until they are resolved!

You will want to look at how you're referencing the favicon files

https://learn-the-web.algonquindesign.ca/topics/image-formats/#placing-the-the-ico-file
