### ISSUE TITLE
Help with accessibility and validation.

### ISSUE THREAD

**Issue by Jessica-Lee123** [Jessica-Lee123/web-design-2-independent-project#2]
@thatkidmadrid
I could use some help with these, say's I'm 93% complete. 
<img width="543" alt="Screen Shot 2021-12-06 at 4 58 16 PM" src="https://user-images.githubusercontent.com/77642609/144929556-7bd08394-7d57-4628-969f-2f9a6da39810.png">

**Comment by thatkidmadrid** [comment]
so the skip-links list should be the very first component inside your body tag - it doesn't need to be inside the `nav` tag that you placed it in. just a `<ul class="skip-links">` with the link in `<li>`s will work here. Please see [the cheatsheet](https://learn-the-web.algonquindesign.ca/topics/accessibility-cheat-sheet/#skip-links) for a common way to style the skip links

You have the class banner, but you also need the role banner for the header

Same comment for the issue with the navigation role

your media query should be written like this
```
@media only screen and (min-width: 60em)
```

the value of 2rem you have is not a good media query value. you will never get a screen smaller than 2 rem...

please see the [cheat sheet for media queries](https://learn-the-web.algonquindesign.ca/topics/screen-sizes-cheat-sheet/)

for the colour contrast, you need to make sure that your fonts are legible with your background. I'll show you a way to check for contrast in class

make sure you have hover and focus states for all your links with obvious changes in style
