### ISSUE TITLE
Accessibility Issue - WAVE

### ISSUE THREAD

**Issue by mmcgreg** [Jessica-Lee123/web-design-2-independent-project#6]
Heyoooo. :)
- skip-link is giving me contrast error issues. Just make sure the text colour is super different to the background colour. You can also hide your skip links using CSS so it doesn't show up on your page!
- Redundant link issue. Seems like you've got multiple links all going to the same place? I can't seem to find exactly where they are in your HTML though...
- Double check your alternate text. It's either insufficient or contains too much info!

**Comment by Jessica-Lee123** [comment]
Thanks so much Morgan! :D
