### ISSUE TITLE
Browser Testing

### ISSUE THREAD

**Issue by mmcgreg** [Jessica-Lee123/web-design-2-independent-project#8]
So I'm not sure where you're at with your CSS but it looks as though you may be coding from a larger screen size than 320px?
When you shrink the browser down to "mobile" size you lose your grid and things become smushed. 
Start small and use media queries to set the sizes of targets as the screen gets bigger :D
![Screen Shot 2021-12-06 at 9 04 43 PM](https://user-images.githubusercontent.com/77412137/144952910-96d38f33-4f26-4998-8b65-9ed56dfc828d.png)
![Screen Shot 2021-12-06 at 9 04 49 PM](https://user-images.githubusercontent.com/77412137/144952919-78c9bc96-9ef5-40ca-a037-2f8299e21ea7.png)

**Comment by Jessica-Lee123** [comment]
I did miss this! I will try to apply it now, thanks so much for taking the time to do this Morgan!
